name: SonarQube Scan (Example)

on:
  push:
    branches: [ "main" ]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube Scan (Placeholder)
        run: |
          echo "This is a reference workflow."
          echo "SonarQube requires a running server and authentication token."
